# Prob 8: Sequence Count

# sequence(n1, n2), n2 is the starting number, n1 is the size of the array
# array is generated by timing n2 with the index+1, and filling out the array

def sequence(n1, n2)

  arr = []
  counter = 1
  
  while n1 >0
    loop do 
      arr << n2 * counter
      counter +=1
      break if counter > n1
    end
    break
  end
arr
end

# Official
def sequence(count, first)
 (1..count).map { |idx| idx * first }
end

p sequence(5, 1) == [1, 2, 3, 4, 5]
p sequence(4, -7) == [-7, -14, -21, -28]
p sequence(3, 0) == [0, 0, 0]
p sequence(0, 1000000) #== []